"""Add image_choice field to post model

Revision ID: 16997182d9ec
Revises: 58702666e07f
Create Date: 2024-12-02 13:47:35.750545

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16997182d9ec'
down_revision = '58702666e07f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_choice', sa.String(length=20), nullable=True))  # Changed to nullable=True
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('image_choice')

    # ### end Alembic commands ###
